matrix:
  include:

    - os: linux
      dist: xenial
      language: python
      python: '3.6'
      deploy:
          provider: pypi
          distributions: sdist
          user: mainro
          password:
            secure: IIDi7NsBeM1JRVT2Jp4RXAyZNBdp3VX8E2TRQdv7Fq29Nm0IdsP5LHcI+rfyu2ZSV7W7LmQuUh+qM1DyCXpERXyc8VnxWLfxeYXc4I8PuNrBDY+JgeWMgGzMQ/VBnbFOMTa1w/DiVSkLMG7YEvhNtDDVQx/JMoMh+u/S9izxQt4VvdDG9xeLsh1ItAERIJwVDvszjglrbJLoeiQ1FTKN99l+ENNVc16pytm/lSCn2zuHhPyffozoC5Jype09Clsd+waUVUcaHlIuu2MY8mtdLckPHy3/5YFmb/0CkXwnuNzwz61SaejQ8HXmlDLqxmXvJqzTE/aCqPZYuCUFt7Sfm8n5vRxn18NDPj5pOKor4QaydVL4WkBCNsKFQKNXbBUyyfpkuvf3olBjJ3lAcP64V9M8vLi4qhBmgfwq9M13dCtWkS0L186nQhQPpaalHiFMn0uXaMGJtlZztOG/PSmqtlOtY5NaFcCF6UQ2opFaHIu8LBbF1FW6b29xIxtBZFjOXyYcky26m7nIUxnMi9ccyi/GA1To5J4kyiY3MycVnkHEvcuC45tL+iKCQLVrHwbdiMbRTs8u6XV5iViPirSaFSgQl5drXG8tS5wRD0L1471vsp9Z/M/VSOZWm5ISVDx9qUvxOm9d1D4aszeqAGSF7yrJ2O9vcJZY17xvDhR6B1o=
          on:
              tags: true

    - os: linux
      dist: xenial
      language: python
      python: '3.7'

    - os: linux
      dist: xenial
      language: python
      python: '3.8-dev'

    - os: osx
      osx_image: xcode10.2
      language: sh
      python: '3.7'

    - os: windows
      language: sh
      python: '3.7'
      before_install:
        - choco install python3
        - ln -s "/c/Python37/python.exe" "/c/Python37/python3.exe"
        - export PATH="/c/Python37:/c/Python37/Scripts/:$PATH"

install:
  - pip3 install nose
  - pip3 install -r requirements.txt
script: nosetests -s --verbosity=3
